name: Deploy to Firebase Hosting

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.38.6

      - name: Install Dependencies
        run: flutter pub get

      - name: Build eyuuncore
        run: |
          cd eyuuncore
          dart run build_runner build
          cd ..

      - name: Build app
        run: |
          dart run build_runner build

      - name: Build Flutter Web
        run: flutter build web --wasm

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project eyuunapp
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
